server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/electronics
    username: root
    password: oct2024
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
  main:
    web-application-type: servlet
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
paypal:
  mode: sandbox
  client:
    app: AUH4L4-7FU3cDolLclbEW3GDlWSA8z5MxmilAQLB7tatwwDdnMndYmucVtAkdRJP6yzDQTBdcI_pUiYu
    secret: EBtY4hZvELr7HYoTUxfOVwDGtJWvT8CmD067eTwRQ_8ZzNat8JhfZQTfEg8ME8gMcXc6LOMmMop5kBwI

